name: deploy-id-server

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: lemonsharp.azurecr.io
        username: lemonsharp
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f "src/Skoruba.IdentityServer4.STS.Identity/Dockerfile" -t lemonsharp.azurecr.io/identityserver:latest -t lemonsharp.azurecr.io/identityserver:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push lemonsharp.azurecr.io/identityserver:latest
        docker push lemonsharp.azurecr.io/identityserver:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.AKS_CONFIG }}
      id: login

    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: lemonsharp.azurecr.io
        container-registry-username: lemonsharp
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: containerregistryauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          k8s/id-server.yaml
        images: |
          lemonsharp.azurecr.io/identityserver:${{ github.sha }}
        imagepullsecrets: |
          containerregistryauth
